export const PRODUCT_CATEGORIES = [
  "Beverages",
  "Soft Drinks",
  "Bottled Water",
  "Alcoholic Drinks",
  "Energy Drinks",
  "Juices",
  "Milk & Dairy",
  "Yogurt",
  "Tea & Coffee",
  "Snacks",
  "Biscuits",
  "Chocolates",
  "Candy",
  "Noodles & Pasta",
  "Rice & Grains",
  "Flour",
  "Sugar",
  "Cooking Oil",
  "Canned Foods",
  "Breakfast Cereals",
  "Spices & Seasoning",
  "Frozen Foods",
  "Bread & Bakery",
  "Eggs",
  "Fruits",
  "Vegetables",
  "Meat",
  "Fish",
  "Condiments",
  "Sauces",
  "Instant Foods",
  "Baby Food",
  "Baby Care",
  "Cleaning Supplies",
  "Laundry Detergent",
  "Dishwashing Liquid",
  "Disinfectants",
  "Air Fresheners",
  "Toiletries",
  "Soap",
  "Shampoo",
  "Toothpaste",
  "Toilet Paper",
  "Sanitary Products",
  "Male Grooming",
  "Skincare",
  "Hair Care",
  "Cosmetics",
  "Stationery",
  "Batteries",
  "Electronics Accessories",
  "Phone Accessories",
  "Light Bulbs",
  "Cooking Gas Accessories",
  "Kitchenware",
  "Plastics",
  "Utensils",
  "Pots & Pans",
  "Home Storage",
  "Pet Food",
  "Pet Care",
  "Medicines (OTC)",
  "Vitamins & Supplements",
  "First Aid",
  "Herbal Products",
  "Insecticides",
  "Pest Control",
  "Car Accessories",
  "Automotive Fluids",
  "Building Materials (Small)",
  "Tools & Hardware",
  "Garden Supplies",
  "Seeds & Fertilizer",
  "Small Appliances",
  "Clothing Essentials",
  "Footwear",
  "Underwear",
  "Socks",
  "Bags",
  "School Supplies",
  "Toys",
  "Games",
  "Gift Items",
  "Religious Items",
  "Candles & Matches",
  "Party Supplies",
  "Decorations",
  "Seasonal Items",
  "Ice Cream",
  "Chilled Drinks",
  "Powdered Milk",
  "Grains & Legumes",
  "Snail / Local Proteins",
  "Beauty Fragrances",
  "Sports Drinks",
  "Health Drinks",
  "Cigarettes",
  "Matches & Lighters",
  "Recharge Cards",
  "POS/Fintech Items",
];
